// This file is automatically generated for ObfusGEM. Do not Edit!


// Error Rate Denominator
static uint64_t err_rate_denom = 100;

// Adder Locking Configuration
static uint64_t adder_lock = 1;
static uint64_t adder_err_rate = 1;
static uint64_t adder_err_severity = 0xffffffff;

// Multiplier Locking Configuration
static uint64_t mult_lock = 0;
static uint64_t mult_err_rate = 0;
static uint64_t mult_err_severity = 0;
