#!/bin/bash

# Load ObfusGEM simulator parameters
source ../obfusgem.conf

# Print Warning Header
echo "// This file is automatically generated for ObfusGEM. Do not Edit!"
echo -e "\n"

# Print obfuscation configuration
echo "// Error Rate Denominator"
echo "static uint64_t err_rate_denom = $err_rate_denom;"
echo ""

echo "// Adder Locking Configuration"
echo "static uint64_t adder_lock = 0;"
echo "static uint64_t adder_err_rate = 0;"
echo "static uint64_t adder_err_severity = 0;"
echo ""

echo "// Multiplier Locking Configuration"
echo "static uint64_t mult_lock = 0;"
echo "static uint64_t mult_err_rate = 0;"
echo "static uint64_t mult_err_severity = 0;"
