#!/bin/bash

# Load ObfusGEM simulator parameters
source ../obfusgem.conf

# Print Warning Header
echo "// This file is automatically generated for ObfusGEM. Do not Edit!"
echo -e "\n"

# Print obfuscation configuration
echo "// Error Rate Denominator"
echo "static uint64_t err_rate_denom = $err_rate_denom;"
echo ""

echo "// Adder Locking Configuration"
echo "static uint64_t adder_lock = $adder_lock;"
echo "static uint64_t adder_err_rate = $adder_err_rate;"
echo "static uint64_t adder_err_severity = $adder_err_severity;"
echo ""

echo "// Multiplier Locking Configuration"
echo "static uint64_t mult_lock = $mult_lock;"
echo "static uint64_t mult_err_rate = $mult_err_rate;"
echo "static uint64_t mult_err_severity = $mult_err_severity;"
